name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Cache CPM Dependencies
      uses: actions/cache@v2
      with:
        key: cache-cpm-dependencies-${{hashFiles('package-lock.cmake')}}
        path: ~/CPMCache
    - name: configure debug
      run: cmake . -B build -G Ninja -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Debug -DCPM_SOURCE_CACHE=~/CPMCache
    - name: build debug
      run: cmake --build build --config Debug
    - name: unittests debug
      run: ./build/bin/Debug/mn_unittest
    - name: configure release
      run: cmake . -B build -G Ninja -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DCPM_SOURCE_CACHE=~/CPMCache
    - name: build release
      run: cmake --build build --config Release
    - name: unittests release
      run: ./build/bin/Release/mn_unittest
